services:
  hrpage:
    build: ../
    container_name: hrpage
    volumes:
      - ./hrpage.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5500:80"
    restart: on-failure

networks:
  default: